### ISSUE TITLE
My components are rendered but not seen like they are hidden

### ISSUE THREAD

**Issue by fselcukcan** [CultureHQ/charts#23]
Can the way importing the css be the problem? I have only showed `import`s that is relevant to the example ntot all, so I import all necessary things.

```
import { HorizontalBarChart, VerticalBarChart, PieChart } from "@culturehq/charts";
import "@culturehq/charts/dist/style.css";

function Dashboard ({ match }) {
        
    return (
	<>
	<IonHeader>
            <IonToolbar color="primary">

	      <IonButtons slot="start">
		<IonMenuButton />
              </IonButtons>
	      
	      <IonTitle>Dashboard</IonTitle>
	      
              <IonButtons slot="end">
		
		<IonButton>
                  <IonIcon name="person" slot="icon-only" />
		</IonButton>
		
              </IonButtons>

	    </IonToolbar>
          </IonHeader>

	  <IonContent>
	    <VerticalBarChart data={{alpha: 1, beta: 3, gamma: 5, delta: 6, epsilon: 0}} />
	  </IonContent>
	</>
    );
}
```

**Comment by kddeisz** [comment]
Can you please share a couple of things in order to help debugging:

1. Your `webpack` (or other bundler) config
2. Your `index.html` file used to serve this app
3. Any global CSS selectors you may have enabled
4. Which browser are you using

Can't do much without more information unfortunately. Are you sure the CSS file is being loaded onto the page?

**Comment by kddeisz** [comment]
Going to close this until it gets more information for tracking purposes.
